baseurl = "https://adam.rbind.io/"
languageCode = "en-us"
title = "Adam's Website"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = "adamofthegarden"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

[params]
    description = "Adam Sadowski's Website."
    footer = "&copy; Adam Sadowski"